export { isConnected } from './setup';
export { initializeVault } from './initializeVault';
export { downloadAFile } from './downloadAFile';
export { uploadEntireNotebook } from './uploadEntireNotebook';
export { vaultUpstream } from './vaultUpstream';
export { vaultDownstream } from './vaultDownstream';
export { addAFile } from './addAFile';
export { deleteAFile } from './deleteAFile';
export { updateAFile } from './updateAFile';
